name: Generate Docs and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docs-deploy:
    name: Generate Docs and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: docs-env
          create-args: >
            doxygen=1.13.2
            graphviz
            perl
          generate-run-shell: true

      - name: Verify Doxygen
        run: doxygen --version
        shell: micromamba-shell {0}

      - name: Generate documentation
        run: |
          perl ./bin/build.pl -d
          echo "Contents of docs folder after generation:"
          ls -R ./docs
        shell: micromamba-shell {0}

      - name: Verify docs exist
        run: |
          if [ -z "$(ls -A ./docs/html)" ]; then
            echo "No docs found! Exiting."
            exit 1
          fi
        shell: micromamba-shell {0}

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
          keep_files: false
