name: Generate Docs and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docs-deploy:
    name: Generate Docs and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y perl doxygen graphviz

      - name: Generate documentation
        run: |
          perl ./bin/build.pl -d
          echo "Contents of docs folder after generation:"
          ls -R ./docs

      - name: Verify docs exist
        run: |
          if [ -z "$(ls -A ./docs/html)" ]; then
            echo "No docs found! Exiting."
            exit 1
          fi

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
          keep_files: false
